# Generated by Django 4.2.7 on 2023-11-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bookinguser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='test', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='test', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='nationality',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookingUser',
        ),
    ]
