# Generated by Django 4.2.7 on 2023-11-28 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_booking_user_booking_email_booking_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='boatschedule',
            old_name='departure_datetime',
            new_name='arrive_time',
        ),
        migrations.AddField(
            model_name='boatschedule',
            name='departure_time',
            field=models.DateTimeField(default='1995-03-02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boatschedule',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='api.location'),
        ),
        migrations.AlterField(
            model_name='boatschedule',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='api.location'),
        ),
    ]
