version: '3.3'

networks:
    internal_app:
        external: false
  
volumes:
    media: {}
    static: {}
    graph_db: {}
    db: {}

services: 
    db:
        container_name: ${PROJECT_NAME}-db
        image: postgres:12.17
        env_file:
            - .env
        volumes:
            - db:/var/lib/postgresql/data

    frontend:
        container_name: ${PROJECT_NAME}-frontend
        build: ./frontend
        command: sh run.sh
        volumes: 
            - ./frontend:/code
        ports: 
            - 3000:3000
        env_file: 
            - .env
        networks:
            - internal_app

    backend:
        container_name: ${PROJECT_NAME}-backend
        build: ./backend
        # command: sh runserver.sh
        volumes: 
            - ./backend:/backend
        ports: 
            - 8000:8000
        env_file: 
            - .env
